### Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
### a) Addition of 2 in all the element
### b) Multiply 3 with all the elements
### c) Divide every element by 2

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Array after addition:", arr+2)
print("Array after multiplication:", arr*3)
print("Array after division:", arr/2)


Array after addition: [3 4 5 6 7]
Array after multiplication: [ 3  6  9 12 15]
Array after division: [0.5 1.  1.5 2.  2.5]


### Q.2 Questions on Basic NumPy Array:
### a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
### b) Find the most frequent value and their indice(s) in the following arrays:
### i. x = np.array([1,2,3,4,5,1,2,1,1,1])
### ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.flip(arr)
print("Reversed array", arr)

def most_frequent_value_and_indices(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_values = values[counts == max_count]
    indices = {val: np.where(arr == val)[0] for val in most_frequent_values}
    return most_frequent_values, indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
x_values, x_indices = most_frequent_value_and_indices(x)
y_values, y_indices = most_frequent_value_and_indices(y)
print("For array x:")
print(f"Most frequent value(s): {x_values}")
print(f"Indices: {x_indices}")
print("\nFor array y:")
print(f"Most frequent value(s): {y_values}")
print(f"Indices: {y_indices}")

Reversed array [5 4 6 3 2 1]
For array x:
Most frequent value(s): [1]
Indices: {1: array([0, 5, 7, 8, 9])}

For array y:
Most frequent value(s): [1 3]
Indices: {1: array([0, 1, 2]), 3: array([4, 8, 9])}


### Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
### a) Access 1st row, 2nd column
### b) Access 3rd row, 1st column

In [4]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[2,0])

20
70


### Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [5]:
my_array = np.linspace(10, 100, 25)
print("Original Array:\n", my_array)
print("\nArray Properties:")
print(f"Dimensions: {my_array.ndim}")
print(f"Shape: {my_array.shape}")
print(f"Total elements: {my_array.size}")
print(f"Data type: {my_array.dtype}")
print(f"Total bytes consumed: {my_array.nbytes}")
transposed_array = my_array.reshape(25, 1)
print("\nTransposed array using reshape():\n", transposed_array)
print("\nUsing T attribute:\n", my_array.T)

Original Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Array Properties:
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transposed array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


### Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [9]:
ucs420_array = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])
mean_value = np.mean(ucs420_array)
median_value = np.median(ucs420_array)
max_value = np.max(ucs420_array)
min_value = np.min(ucs420_array)
unique_elements = np.unique(ucs420_array)
reshaped_ucs420_AMAN_YADAV = ucs420_array.reshape(4, 3)
resized_ucs420_AMAN_YADAV = np.resize(ucs420_array, (2, 3))
print("Original 2D Array (3x4):\n", ucs420_array)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_AMAN_YADAV)
print("\nResized Array (2x3):\n", resized_ucs420_AMAN_YADAV)

Original 2D Array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
